=== RMajewski/testsuite/src/resources/xml/config.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			xmlns="https://github.com/RMajewski/testsuite"
			targetNamespace="https://github.com/RMajewski/testsuite"
			elementFormDefault="qualified">
    <xsd:annotation>
    	<xsd:documentation>Configuration file schema for testsuite</xsd:documentation>
   	</xsd:annotation>

	<xsd:element name="configurationFile">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="config" type="configType" minOccurs="0" maxOccurs="1"/>
				<xsd:element name="testGroup" type="testGroupType" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="configType">
		<xsd:sequence>
			<xsd:element name="resultPath" minOccurs="0" type="xsd:string"/>
			<xsd:element name="srcPath" minOccurs="1" type="xsd:string"/>
			<xsd:element name="libPath" minOccurs="0" type="xsd:string"/>
			<xsd:element name="maxDuration" minOccurs="0" type="xsd:long"/>
			<xsd:element name="htmlOut" minOccurs="0" type="xsd:boolean"/>
			<xsd:element name="systemProperty" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="property" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="classpath" minOccurs="0" type="classpathType" />
		</xsd:sequence>
	</xsd:complexType>
		
	<xsd:complexType name="testGroupType">
		<xsd:sequence>
			<xsd:element name="testRunner" type="xsd:string" minOccurs="1"/>
			<xsd:element name="description" type="xsd:string" minOccurs="1"/>
			<xsd:element name="extension" type="xsd:string" minOccurs="1"/>
			<xsd:element name="libraries" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="library" maxOccurs="unbounded" minOccurs="1">
							<xsd:complexType>
								<xsd:simpleContent>
									<xsd:extension base="xsd:string">
										<xsd:attribute name="version" type="xsd:string" />
										<xsd:attribute name="name" type="xsd:string"/>
										<xsd:attribute name="path" type="xsd:string"/>
									</xsd:extension>
								</xsd:simpleContent>
							</xsd:complexType>
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="classpath" minOccurs="0" type="classpathType" />
			<xsd:element name="testSuite" minOccurs="1" maxOccurs="unbounded" type="testSuiteType" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="classpathType">
		<xsd:sequence>
			<xsd:element name="path" type="xsd:string" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="testSuiteType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" minOccurs="1"/>
			<xsd:element name="package" type="xsd:string" minOccurs="1"/>
			<xsd:element name="test" minOccurs="1" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:simpleContent>
						<xsd:extension base="xsd:string">
							<xsd:attribute name="executed" type="xsd:boolean"/>
						</xsd:extension>
					</xsd:simpleContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== RMajewski/testsuite/src/tests/test_checksource.xml
<?xml version="1.0"?>
<configurationFile xmlns="https://github.com/RMajewski/testsuite"
				   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				   xsi:schemaLocation="https://github.com/RMajewski/testsuite
				   https://raw.githubusercontent.com/RMajewski/testsuite/master/src/resources/xml/config.xsd">
	<config>
		<resultPath>result</resultPath>
		<srcPath>src</srcPath>
		<libPath>..</libPath>
		<maxDuration>30000</maxDuration>
		<htmlOut>true</htmlOut>
		<systemProperty>
			<property>testing="true"</property>
		</systemProperty>
		<classpath>
			<path>bin</path>
		</classpath>
		<stylesheet>
			<file>resources/html/out.css</file>
			<file>resources/html/checksource.css</file>
		</stylesheet>
		<javascript>
			<file>resources/html/out.js</file>
		</javascript>
		<todo>
			<name>OPT</name>
			<name>FIX</name>
			<name>TODO</name>
		</todo>
		<checkSourceConfig>
			<noneTestedList path="src/org">true</noneTestedList>
			<lineWidth tabSpace="4">80</lineWidth>
			<parser timeout="20000" parse="true">org.testsuite.checksource.JdbParser</parser>
			<path>org.testsuite.checksource.tests</path>
			<test>TestEmptyLines</test>
			<test>TestEmptyMethod</test>
			<test>TestJavadoc</test>
			<test>TestToWideLines</test>
			<test>TestUnusedImports</test>
		</checkSourceConfig>
	</config>
	
	<testGroup>
		<testRunner>org.testsuite.core.JunitTestRunner</testRunner>
		<description>[h2]Tests the check source[/h2][p]Tests the classes of checksource package with JUnit.[/p]</description>
		<extension>java</extension>
		<libraries>
			<library version="4.12" name="junit" path="/usr/share/eclipse/plugins/org.junit_4.12.0.v201504281640">junit.jar</library>
			<library version="1.10.19" name="Mockito">mockito-all-1.10.19.jar</library>
			<library version="1.6.3" name="PowerMockito">powermock-mockito-1.6.3-full.jar</library>
			<library version="2.2.2" name="cglib">cglib-nodep-2.2.2.jar</library>
			<library version="3.20.0" name="javassist">javassist-3.20.0-GA.jar</library>
			<library version="2.1" name="objenesis">objenesis-2.1.jar</library>
			<library version="1.3.0" name="hamcrest" path="/usr/share/eclipse/plugins/">org.hamcrest.core_1.3.0.v201303031735.jar</library>
		</libraries>
		<testSuite>
			<name>Tests the English language files</name>
			<package>tests.lang.en</package>
			<test>TestChecksourceHtmlOut</test>
			<test>TestChecksourceTests</test>
		</testSuite>
		<testSuite>
			<name>Tests the German language files</name>
			<package>tests.lang.de_DE</package>
			<test>TestChecksourceHtmlOut_de</test>
			<test>TestChecksourceTests_de</test>
		</testSuite>
		<testSuite>
			<name>Tests the class of helper</name>
			<package>tests.testsuite.helper</package>
			<test checkSource="org.testsuite.helper.HelperHtml">TestHelperHtml</test>
			<test checkSource="org.testsuite.helper.HelperHtmlCodeJava">TestHelperHtmlCodeJava</test>
			<test checkSource="org.testsuite.helper.HelperUsedColor">TestHelperUsedColor</test>
		</testSuite>
		<testSuite>
			<name>Tests the annotations</name>
			<package>tests.testsuite.checksource.annotation</package>
			<test checkSource="org.testsuite.checksource.annotation.CheckSource">TestCheckSource</test>
		</testSuite>
		<testSuite>
			<name>Tests the classes of configuration</name>
			<package>tests.testsuite.checksource</package>
			<test checkSource="org.testsuite.checksource.CSConfig">TestCSConfig</test>
		</testSuite>
		<testSuite>
			<name>Tests the classes of informations</name>
			<package>tests.testsuite.checksource</package>
			<test checkSource="org.testsuite.checksource.CSMethod">TestCSMethod</test>
			<test checkSource="org.testsuite.checksource.CSParameter">TestCSParameter</test>
			<test checkSource="org.testsuite.checksource.MessageColor">TestMessageColor</test>
		</testSuite>
		<testSuite>
			<name>Tests the classes for read the source files</name>
			<package>tests.testsuite.checksource</package>
			<test checkSource="org.testsuite.checksource.Read">TestRead</test>
			<test checkSource="org.testsuite.checksource.ReadSource">TestReadSource</test>
			<test checkSource="org.testsuite.checksource.ReadTest">TestReadTest</test>
			<test checkSource="org.testsuite.checksource.SourceLine">TestSourceLine</test>
			<test checkSource="org.testsuite.checksource.SourceFile">TestSourceFile</test>
		</testSuite>
		<testSuite>
			<name>Tests the classes for parser</name>
			<package>tests.testsuite.checksource</package>
			<test checkSource="org.testsuite.checksource.Parser">TestParser</test>
			<test checkSource="org.testsuite.checksource.JdbParser">TestJdbParser</test>
		</testSuite>
		<testSuite>
			<name>Tests the classes for check source</name>
			<package>tests.testsuite.checksource</package>
			<test checkSource="org.testsuite.checksource.CheckSource">TestCheckSource</test>
		</testSuite>
		<testSuite>
			<name>Tests the output</name>
			<package>tests.testsuite.checksource.html</package>
			<test checkSource="org.testsuite.checksource.html.Html">TestHtml</test>
			<test checkSource="org.testsuite.checksource.html.HtmlOut">TestHtmlOut</test>
			<test checkSource="org.testsuite.checksource.html.HtmlOutOverview">TestHtmlOutOverview</test>
			<test checkSource="org.testsuite.checksource.html.HtmlDeprecated">TestHtmlDeprecated</test>
			<test checkSource="org.testsuite.checksource.html.HtmlMenu">TestHtmlMenu</test>
			<test checkSource="org.testsuite.checksource.html.HtmlNoneExistFile">TestHtmlNoneExistFile</test>
			<test checkSource="org.testsuite.checksource.html.HtmlNoneTestedMethods">TestHtmlNoneTestedMethods</test>
			<test checkSource="org.testsuite.checksource.html.HtmlNoneTestedSourceFiles">TestHtmlNoneTestedSourceFiles</test>
			<test checkSource="org.testsuite.checksource.html.HtmlTodo">TestHtmlTodo</test>
		</testSuite>
		<testSuite>
			<name>Tests for check source tests</name>
			<package>tests.testsuite.checksource.tests</package>
			<test checkSource="org.testsuite.checksource.tests.SourceTest">TestSourceTest</test>
			<test checkSource="org.testsuite.checksource.tests.TestEmptyLines">TestTestEmptyLines</test>
			<test checkSource="org.testsuite.checksource.tests.TestEmptyMethod">TestTestEmptyMethod</test>
			<test checkSource="org.testsuite.checksource.tests.TestUnusedImports">TestTestUnusedImports</test>
			<test checkSource="org.testsuite.checksource.tests.TestJavadoc">TestTestJavadoc</test>
			<test checkSource="org.testsuite.checksource.tests.TestToWideLines">TestTestToWideLines</test>
		</testSuite>
	</testGroup>
</configurationFile>

=== RMajewski/testsuite/src/tests/test.xml
<?xml version="1.0"?>
<configurationFile xmlns="https://github.com/RMajewski/testsuite"
				   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				   xsi:schemaLocation="https://github.com/RMajewski/testsuite
				   https://raw.githubusercontent.com/RMajewski/testsuite/master/src/resources/xml/config.xsd">
	<config>
		<resultPath>result</resultPath>
		<srcPath>src</srcPath>
		<libPath>..</libPath>
		<maxDuration>30000</maxDuration>
		<htmlOut>true</htmlOut>
		<lineWidth>80</lineWidth>
		<systemProperty>
			<property>testing="true"</property>
		</systemProperty>
		<classpath>
			<path>bin</path>
		</classpath>
		<stylesheet>
			<file>resources/html/out.css</file>
		</stylesheet>
		<javascript>
			<file>resources/html/out.js</file>
		</javascript>
	</config>
	
	<testGroup>
		<testRunner>org.testsuite.core.JemmyTestRunner</testRunner>
		<description>[h2]Test with jemmy[/h2][p]This is are tests with jemmy framework.[/p]</description>
		<extension>java</extension>
		<libraries>
			<library version="2.3.1.1" name="jemmy">jemmy.jar</library>
		</libraries>
	</testGroup>
	
	<testGroup>
		<testRunner>org.testsuite.core.JunitTestRunner</testRunner>
		<description>[h2]Test with junit[/h2][p]This are tests with junit framework.[/p]</description>
		<extension>java</extension>
		<libraries>
			<library version="4.12" name="junit" path="/usr/share/eclipse/plugins/org.junit_4.12.0.v201504281640">junit.jar</library>
			<library version="1.10.19" name="Mockito">mockito-all-1.10.19.jar</library>
			<library version="1.6.3" name="PowerMockito">powermock-mockito-1.6.3-full.jar</library>
			<library version="2.2.2" name="cglib">cglib-nodep-2.2.2.jar</library>
			<library version="3.20.0" name="javassist">javassist-3.20.0-GA.jar</library>
			<library version="2.1" name="objenesis">objenesis-2.1.jar</library>
			<library version="1.3.0" name="hamcrest" path="/usr/share/eclipse/plugins/">org.hamcrest.core_1.3.0.v201303031735.jar</library>
		</libraries>
		<testSuite>
			<name>Test org.testsuite.App</name>
			<package>tests.testsuite.app</package>
			<test checkSource="org.testsuite.app.AppTreeModel">TestAppTreeModel</test>
			<test checkSource="org.testsuite.app.DlgConfig">TestDlgConfig</test>
			<test checkSource="org.testsuite.app.ValidationEvent">TestValidationEvent</test>
		</testSuite>
		<testSuite>
			<name>Test org.testsuite.Core</name>
			<package>tests.testsuite.core</package>
			<test checkSource="org.testsuite.core.ConfigParser">TestConfigParser</test>
			<test checkSource="org.testsuite.core.ConfigSaver">TestConfigSaver</test>
			<test checkSource="org.testsuite.core.TestRunner">TestTestRunner</test>
			<test checkSource="org.testsuite.core.FitTestRunner">TestFitTestRunner</test>
			<test checkSource="org.testsuite.core.JemmyTestRunner">TestJemmyTestRunner</test>
			<test checkSource="org.testsuite.core.JunitTestRunner">TestJunitTestRunner</test>
			<test checkSource="org.testsuite.core.HtmlOut">TestHtmlOut</test>
			<test checkSource="org.testsuite.core.TestCore">TestTestCore</test>
			<test checkSource="org.testsuite.core.TestsRun">TestTestsRun</test>
		</testSuite>
		<testSuite>
			<name>Test org.testsuite.Data</name>
			<package>tests.testsuite.data</package>
			<test checkSource="org.testsuite.data.Config">TestConfig</test>
			<test checkSource="org.testsuite.data.TestEvent">TestTestEvent</test>
			<test checkSource="org.testsuite.data.TestSelectEvent">TestTestSelectEvent</test>
			<test checkSource="org.testsuite.data.TestEventListener">TestTestEventListener</test>
			<test checkSource="org.testsuite.data.Data">TestData</test>
			<test checkSource="org.testsuite.data.Fit">TestFitData</test>
			<test checkSource="org.testsuite.data.Junit">TestJunitData</test>
			<test checkSource="org.testsuite.data.Library">TestLibrary</test>
			<test checkSource="org.testsuite.data.Test">TestTest</test>
			<test checkSource="org.testsuite.data.TestSuite">TestTestSuite</test>
		</testSuite>
		<testSuite>
			<name>Test org.testsuite.Helper</name>
			<package>tests.testsuite.helper</package>
			<test checkSource="org.testsuite.helper.HelperCalendar">TestHelperCalendar</test>
			<test checkSource="org.testsuite.helper.HelperHtml">TestHelperHtml</test>
			<test checkSource="org.testsuite.helper.HelperHtmlCodeJava">TestHelperHtmlCodeJava</test>
			<test checkSource="org.testsuite.helper.HelperUsedColor">TestHelperUsedColor</test>
		</testSuite>
		<testSuite>
			<name>Tests the English language files</name>
			<package>tests.lang.en</package>
			<test>TestApp</test>
			<test>TestDlgConfigGeneral</test>
			<test>TestDlgConfigLibrary</test>
			<test>TestDlgConfigTest</test>
			<test>TestDlgConfigTestRunner</test>
			<test>TestDlgConfigTestSuite</test>
			<test>TestHtmlOut</test>
			<test>TestTestCore</test>
			<test>TestTestRunner</test>
			<test>TestValidationEventRenderer</test>
			<test>TestChecksourceHtmlOut</test>
			<test>TestChecksourceTests</test>
		</testSuite>
		<testSuite>
			<name>Tests the German language files</name>
			<package>tests.lang.de_DE</package>
			<test>TestApp_de</test>
			<test>TestDlgConfigGeneral_de</test>
			<test>TestDlgConfigLibrary_de</test>
			<test>TestDlgConfigTest_de</test>
			<test>TestDlgConfigTestRunner_de</test>
			<test>TestDlgConfigTestSuite_de</test>
			<test>TestHtmlOut_de</test>
			<test>TestTestCore_de</test>
			<test>TestTestRunner_de</test>
			<test>TestValidationEventRenderer_de</test>
			<test>TestChecksourceHtmlOut_de</test>
			<test>TestChecksourceTests_de</test>
		</testSuite>
		<testSuite>
			<name>Tests the annotations</name>
			<package>tests.testsuite.checksource.annotation</package>
			<test checkSource="org.testsuite.checksource.CheckSource">TestCheckSource</test>
		</testSuite>
		<testSuite>
			<name>Tests for check source tests</name>
			<package>tests.testsuite.checksource.tests</package>
			<test checkSource="org.testsuite.checksource.tests.SourceTest">TestSourceTest</test>
			<test checkSource="org.testsuite.checksource.tests.TestEmptyLines">TestTestEmptyLines</test>
			<test checkSource="org.testsuite.checksource.tests.TestEmptyMethod">TestTestEmptyMethod</test>
			<test checkSource="org.testsuite.checksource.tests.TestUnusedImports">TestTestUnusedImports</test>
			<test checkSource="org.testsuite.checksource.tests.TestJavadoc">TestTestJavadoc</test>
		</testSuite>
		<testSuite>
			<name>Tests the check source</name>
			<package>tests.testsuite.checksource</package>
			<test checkSource="org.testsuite.checksource.CSMethod">TestCSMethod</test>
			<test checkSource="org.testsuite.checksource.CSParameter">TestCSParameter</test>
			<test checkSource="org.testsuite.checksource.MessageColor">TestMessageColor</test>
			<test checkSource="org.testsuite.checksource.Read">TestRead</test>
			<test checkSource="org.testsuite.checksource.ReadSource">TestReadSource</test>
			<test checkSource="org.testsuite.checksource.ReadTest">TestReadTest</test>
			<test checkSource="org.testsuite.checksource.SourceLine">TestSourceLine</test>
			<test checkSource="org.testsuite.checksource.SourceFile">TestSourceFile</test>
			<test checkSource="org.testsuite.checksource.CheckSource">TestCheckSource</test>
			<test checkSource="org.testsuite.checksource.Html">TestHtml</test>
			<test checkSource="org.testsuite.checksource.HtmlOut">TestHtmlOut</test>
			<test checkSource="org.testsuite.checksource.HtmlOutOverview">TestHtmlOutOverview</test>
		</testSuite>
	</testGroup>
	
	<testGroup>
		<testRunner>org.testsuite.core.FitTestRunner</testRunner>
		<description>[h2]Tests with FIT[/h2][p]This are tests with fit framemwork.[/p]</description>
		<extension>fit</extension>
		<libraries>
			<library version="2.3.1.1" name="jemmy">jemmy.jar</library>
		</libraries>
		<testSuite>
			<name>Test fit</name>
			<package>tests.fit.fit</package>
			<test>FitFixtureRun</test>
		</testSuite>
		<testSuite>
			<name>Test the class org.testsuite.app.App</name>
			<package>tests.fit.app</package>
			<test>AppElementsCreated</test>
			<test>AppButtonsRightEnabled</test>
			<test>AppConfigurationLoad</test>
			<test>AppConfigurationSave</test>
			<test>AppConfigurationValidate</test>
			<test>AppTree</test>
			<test>AppRunTests</test>
			<test>AppCancelRunTests</test>
			<test>AppCreateHtmlOut</test>
			<test>AppReadHtmlOut</test>
			<test>AppTreePopupIsRightEnabled</test>
			<test>AppChangeGeneralConfiguration</test>
			<test>AppGeneralConfigurationProperties</test>
			<test>AppGeneralConfigurationClassPaths</test>
			<test>AppGeneralConfigurationJavascript</test>
			<test>AppGeneralConfigurationStylesheet</test>
			<test>AppTreeInsertTestRunner</test>
			<test>AppTreeDeleteTestRunner</test>
			<test>AppTestRunnerAllOtherTestsIgnored</test>
			<test>AppTestRunnerAllTestsExecuted</test>
			<test>AppTestRunnerAllTestsIgnored</test>
			<test>AppTestRunnerConfiguration</test>
			<test>AppTestRunnerConfigurationClasspathPopup</test>
			<test>AppTestRunnerConfigurationLibraryPopup</test>
			<test>AppLibraryConfiguration</test>
			<test>AppTreeInsertTestSuite</test>
			<test>AppTreeDeleteTestSuite</test>
			<test>AppTestSuiteAllOtherTestsIgnored</test>
			<test>AppTestSuiteAllTestsExecuted</test>
			<test>AppTestSuiteAllTestsIgnored</test>
			<test>AppTestSuiteConfiguration</test>
			<test>AppTreeInsertTest</test>
			<test>AppTreeDeleteTest</test>
			<test>AppTestConfiguration</test>
			<test>AppTestAllOtherTestsIgnored</test>
			<test>AppAllTestsExecuted</test>
			<test>AppAllTestsIgnored</test>
		</testSuite>
	</testGroup>
</configurationFile>

=== RMajewski/testsuite/src/tests/junit_test.xml
<?xml version="1.0"?>
<configurationFile xmlns="https://github.com/RMajewski/testsuite"
				   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				   xsi:schemaLocation="https://github.com/RMajewski/testsuite
				   https://raw.githubusercontent.com/RMajewski/testsuite/master/src/resources/xml/config.xsd">
	<config>
		<resultPath>result</resultPath>
		<srcPath>src</srcPath>
		<libPath>..</libPath>
		<maxDuration>30000</maxDuration>
		<htmlOut>true</htmlOut>
		<systemProperty>
			<property>testing="true"</property>
		</systemProperty>
		<classpath>
			<path>bin</path>
		</classpath>
		<stylesheet>
			<file>resources/html/out.css</file>
		</stylesheet>
		<javascript>
			<file>resources/html/out.js</file>
		</javascript>
	</config>
	
	<testGroup>
		<testRunner>org.testsuite.core.JunitTestRunner</testRunner>
		<description>[h2]Test with junit[/h2][p]This are tests with junit framework.[/p]</description>
		<extension>java</extension>
		<libraries>
			<library version="4.12" name="junit" path="/usr/share/eclipse/plugins/org.junit_4.12.0.v201504281640">junit.jar</library>
			<library version="1.10.19" name="Mockito">mockito-all-1.10.19.jar</library>
			<library version="1.6.3" name="PowerMockito">powermock-mockito-1.6.3-full.jar</library>
			<library version="2.2.2" name="cglib">cglib-nodep-2.2.2.jar</library>
			<library version="3.20.0" name="javassist">javassist-3.20.0-GA.jar</library>
			<library version="2.1" name="objenesis">objenesis-2.1.jar</library>
			<library version="1.3.0" name="hamcrest" path="/usr/share/eclipse/plugins/">org.hamcrest.core_1.3.0.v201303031735.jar</library>
		</libraries>
		<testSuite>
			<name>Test org.testsuite.Core</name>
			<package>tests.testsuite.core</package>
			<test>TestConfigParser</test>
		</testSuite>
		<testSuite>
			<name>Test org.testsuite.Data</name>
			<package>tests.testsuite.data</package>
			<test jvm="false">TestConfig</test>
			<test>TestTest</test>
		</testSuite>
	</testGroup>
</configurationFile>
